version: "3"
services:
    gcc:
        container_name: google-closure-compiler
        working_dir: /var/www/html
        build: .
        volumes:
            - .:/var/www/html:delegated
        ports:
            - "83:83"
